<?php
/**
 * This is the default template for the Easy Value Added Taxes
 * element in the totals loop of the content-confirmation
 * template part. It was added by Easy UValue Added Taxes add-on.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package exchange-addon-easy-value-added-taxes
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_confirmation_before_transaction_vat_summary' ); ?>
<div class="it-exchange-vat-summary">
	<?php it_exchange( 'value-added-taxes', 'vat-summary' ); ?>
</div>
<?php do_action( 'it_exchange_confirmation_after_transaction_vat_summary' ); ?>
