<?php
/**
 * This is the default template part for the
 * cancel element in the actions loop for the
 * shipping address purchase-requriements in the
 * content-checkout template part.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file to the
 * /exchange/content-checkout/elements/purchase-requirements/customer-eu-vat-number/elements/
 * directory located in your theme.
*/
?>
<?php do_action( 'it_exchange_content_checkout_customer_eu_vat_number_purchase_requirement_before_cancel_element' ); ?>
<div class="it-exchange-cancel-element">
	<?php it_exchange( 'value-added-taxes', 'cancel' ); ?>
</div>
<?php do_action( 'it_exchange_content_checkout_customer_eu_vat_number_purchase_requirement_after_cancel_element' ); ?>
