<?php
/**
 * This is the default template for the Easy EU Value Added Taxes
 * element in the totals loop of the content-checkout
 * template part. It was added by Easy EU Value Added Taxes add-on.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package exchange-addon-easy-eu-value-added-taxes
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-checkout/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_cart_before_easy_eu_valued_added_taxes_element' ); ?>
<?php it_exchange( 'eu-value-added-taxes', 'taxes' ); ?>
<?php do_action( 'it_exchange_content_cart_after_easy_eu_valued_added_taxes_element' ); ?>
